"""upgrade question model

Revision ID: 006c7ac62008
Revises: f60f63a9cf98
Create Date: 2026-07-20 16:21:21.404300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006c7ac62008'
down_revision: Union[str, Sequence[str], None] = 'f60f63a9cf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(length=30), nullable=True))
    op.add_column('questions', sa.Column('exam_stage', sa.String(length=30), nullable=True))
    op.add_column('questions', sa.Column('is_pyq', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_pyq')
    op.drop_column('questions', 'exam_stage')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'language')
    # ### end Alembic commands ###
