"""create question options

Revision ID: 1cbeeee9daeb
Revises: 6891758afc31
Create Date: 2026-07-28 15:45:21.061491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbeeee9daeb'
down_revision: Union[str, Sequence[str], None] = '6891758afc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Create the new question_options table
    op.create_table(
        'question_options',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('option_text', sa.String(length=500), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_question_options_id'),
        'question_options',
        ['id'],
        unique=False,
    )

    op.create_index(
        op.f('ix_question_options_question_id'),
        'question_options',
        ['question_id'],
        unique=False,
    )

    op.alter_column(
        'questions',
        'difficulty',
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )

    op.alter_column(
        'questions',
        'question_type',
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
    )

    op.alter_column(
        'questions',
        'exam_stage',
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
    )

    op.alter_column(
        'questions',
        'estimated_time',
        existing_type=sa.INTEGER(),
        nullable=False,
    )

    op.alter_column(
        'questions',
        'language',
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )

    op.alter_column(
        'questions',
        'is_pyq',
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )

    op.alter_column(
        'questions',
        'is_active',
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )

    op.create_index(
        op.f('ix_questions_topic_id'),
        'questions',
        ['topic_id'],
        unique=False,
    )

    # IMPORTANT:
    # We are NOT dropping old option columns yet.
    # We will first migrate the data safely in the next step.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('option_c', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_a', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_b', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_d', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('correct_option', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.alter_column('questions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('questions', 'is_pyq',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('questions', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('questions', 'estimated_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'negative_marks',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'marks',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'exam_stage',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_index(op.f('ix_question_options_id'), table_name='question_options')
    op.drop_table('question_options')
    # ### end Alembic commands ###
    # ----------------------------
    # Migrate existing options
    # ----------------------------

    op.execute("""
        INSERT INTO question_options (question_id, option_text, display_order, is_correct)
        SELECT id, option_a, 1,
            CASE WHEN correct_option = 'A' THEN TRUE ELSE FALSE END
        FROM questions
        WHERE option_a IS NOT NULL;
    """)

    op.execute("""
        INSERT INTO question_options (question_id, option_text, display_order, is_correct)
        SELECT id, option_b, 2,
            CASE WHEN correct_option = 'B' THEN TRUE ELSE FALSE END
        FROM questions
        WHERE option_b IS NOT NULL;
    """)

    op.execute("""
        INSERT INTO question_options (question_id, option_text, display_order, is_correct)
        SELECT id, option_c, 3,
            CASE WHEN correct_option = 'C' THEN TRUE ELSE FALSE END
        FROM questions
        WHERE option_c IS NOT NULL;
    """)

    op.execute("""
        INSERT INTO question_options (question_id, option_text, display_order, is_correct)
        SELECT id, option_d, 4,
            CASE WHEN correct_option = 'D' THEN TRUE ELSE FALSE END
        FROM questions
        WHERE option_d IS NOT NULL;
    """)