"""add question metadata

Revision ID: b5b40435a3ea
Revises: 006c7ac62008
Create Date: 2026-07-20 16:32:59.369731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b40435a3ea'
down_revision: Union[str, Sequence[str], None] = '006c7ac62008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('questions', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'image_url')
    op.drop_column('questions', 'hint')
    op.drop_column('questions', 'estimated_time')
    op.drop_column('questions', 'tags')
    # ### end Alembic commands ###
